#
###################################
# Site wide configuration
####################################
#
title: justiceserv
email: justiceserv@justiceserv.dev
description: 정구현의 개인적인 코딩 블로그입니다. 
url: #
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: justiceserv
  avatar: leonids-logo.png
  job: "Student"
  bio: "제 개인적인 코딩 블로그입니다."
  email: justiceserv@justiceserv.dev
  disqus-shortname:
  twitter: R6S_StSinsa
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: justiceserv
  gitlab: #username
  stackoverflow: 12413689/justiceserv
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
